// RootLayout.jsx

import '@fontsource/inter'; // Importing Inter font styles
import Navbar from '../../components/Navbar';
import Navigation from '../../components/Navigation';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className='flex max-w-screen-xl mx-auto p-4'>
      <Navigation /> {/* Include the side navigation component */}
      <div className='flex-1'>
        <Navbar />
        <div className='mt-8'>{children}</div>
      </div>
    </div>
  );
}
